kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
  extraMounts:
    - hostPath: ./jars
      containerPath: /foo/jars
  extraPortMappings:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
- role: worker
  extraMounts:
    - hostPath: ./jars
      containerPath: /foo/jars
- role: worker
  extraMounts:
    - hostPath: ./jars
      containerPath: /foo/jars
