apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-zookeeper-deployment
  labels:
    {{- include "insight-hoot-chart.labels" . | nindent 4}}
    app: {{ .Values.kafka.labels.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.kafka.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.kafka.labels.app }}
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.0.1
        ports:
        - containerPort: {{ .Values.kafka.Zookeeper.ContainerPort }} 
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "{{ .Values.kafka.Zookeeper.ContainerPort }}"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
 
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-zookeeper-service
  labels:
    {{- include "insight-hoot-chart.labels" . | nindent 4 }}
    app: {{ .Values.kafka.labels.app }}
spec:
  selector:
    app: {{ .Values.kafka.labels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.kafka.Zookeeper.ContainerPort }}
      targetPort: {{ .Values.kafka.Zookeeper.ContainerPort }}
