apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kafka-ui-deployment
  labels:
    {{- include "insight-hoot-chart.labels" . | nindent 4 }}
    app: {{ .Values.psql.labels.app }}
  # namespace: mstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.psql.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.psql.labels.app }}
    spec:
      containers:
      - name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        env:
        - name: KAFKA_CLUSTERS_0_NAME
          value: "K8 Kafka Cluster"
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: kafka-service:{{ .Values.kafka.Kafka.ContainerPort }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
        - containerPort: {{ .Values.kafka.KafkaUI.Port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka-ui-service
spec:
  selector:
    app: kafka-ui
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.kafka.KafkaUI.Port }}
      targetPort: {{ .Values.kafka.KafkaUI.Port }}
      nodePort: 31006
