apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.psql.pgConfigmap.name }}
  labels:
    app: {{.Values.psql.labels.app}}
data:
  POSTGRES_DB: mydatabase
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: mysecretpassword
