name: Packaging
run-name: ${{github.actor}} on ${{github.event_name}} launch sbt-packaging
on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']


jobs:
  sbt-build-jar:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.12.18]
        java: [temurin@8]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java (temurin@8)
        if: matrix.java == 'temurin@8'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: sbt


      - name: Test project
        run: |
          cd InsightHoot
          sbt '++ ${{ matrix.scala }}' test
      - name: Assembly project
        run: |
          cd InsightHoot
          sbt '++ ${{ matrix.scala }}' assembly

      - name: Upload target directories
        uses: actions/upload-artifact@v4
        with:
          name: target-${{ matrix.os }}-${{ matrix.scala }}-${{ matrix.java }}
          path: InsightHoot/targets.tar

